services:
  db:
    container_name: blogy
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogy
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/blogy:/var/lib/postgresql/data
